location / {
    proxy_pass https://localhost:8443;
    include    proxy_params_no_auth;

    # Pass large request bodies (e.g. firmware uploads to controller)
    client_max_body_size 0;
}

location /wss/ {
    proxy_pass https://localhost:8443;
    include    proxy_params_no_auth;
}